### ISSUE TITLE
unhandled 'error' event

### ISSUE THREAD

**Issue by fraserxu** [peter-vilja/gulp-clean#7]
I got this error while running `gulp clean` task.

``` javascript
// Clean.
gulp.task('clean', function() {
    gulp.src(['client/dist'], {read: false}).pipe(clean());
});
```

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Unable to delete "/Users/fraserxu/work/Octokan/client/dist" file (ENOTEMPTY, rmdir '/Users/fraserxu/work/Octokan/client/dist/assets/fonts').
    at /Users/fraserxu/work/Octokan/node_modules/gulp-clean/index.js:20:21
    at CB (/Users/fraserxu/work/Octokan/node_modules/gulp-clean/node_modules/rimraf/rimraf.js:42:5)
    at /Users/fraserxu/work/Octokan/node_modules/gulp-clean/node_modules/rimraf/rimraf.js:135:18
    at CB (/Users/fraserxu/work/Octokan/node_modules/gulp-clean/node_modules/rimraf/rimraf.js:42:5)
    at /Users/fraserxu/work/Octokan/node_modules/gulp-clean/node_modules/rimraf/rimraf.js:135:18
    at CB (/Users/fraserxu/work/Octokan/node_modules/gulp-clean/node_modules/rimraf/rimraf.js:42:5)
    at Object.oncomplete (fs.js:107:15)
```

**Comment by DominicTobias** [comment]
I get the same issue too even when returning the stream, I get it with all the gulp clean type plugins I have tried actually, but not with any grunt ones

**Comment by dwelch2344** [comment]
+1 to getting this suddenly. Maybe a change in the way gulp operates?

**Comment by dimatter** [comment]
bump
